{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "userdev",
    "version": "7.0.5+asset-redownload",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-userdev",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "userdev-7.0.5+asset-redownload.jar",
          "url": "userdev-7.0.5+asset-redownload.jar",
          "size": 49188,
          "sha512": "79dfdcda62a43ed12b2ce868969f294fcd14f4c080961013d6a2a101d9fb815583f2876429ee41f689c5c23704b25b18fe3e72d6a9fe32f7b728c7145bb343d7",
          "sha256": "0fed2ac14fe661fb361e080dc1ff45a3186cb54d89fb2715fc31bc79a1f98b98",
          "sha1": "31c6f635f62f0077426be67198c37a6ddcc4ec27",
          "md5": "f8667c10f466d3f447a3fa0adc51a7e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-userdev",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "userdev-7.0.5+asset-redownload.jar",
          "url": "userdev-7.0.5+asset-redownload.jar",
          "size": 49188,
          "sha512": "79dfdcda62a43ed12b2ce868969f294fcd14f4c080961013d6a2a101d9fb815583f2876429ee41f689c5c23704b25b18fe3e72d6a9fe32f7b728c7145bb343d7",
          "sha256": "0fed2ac14fe661fb361e080dc1ff45a3186cb54d89fb2715fc31bc79a1f98b98",
          "sha1": "31c6f635f62f0077426be67198c37a6ddcc4ec27",
          "md5": "f8667c10f466d3f447a3fa0adc51a7e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "userdev-7.0.5+asset-redownload-sources.jar",
          "url": "userdev-7.0.5+asset-redownload-sources.jar",
          "size": 21523,
          "sha512": "ee2cca4762018467df2d740fe690c0b30d8fd19f486c2905aaaad16848867feb3eec2b577e64bdc878ec2a00af36985b58b3f8d0182ba19c6a3f7d27c66931e9",
          "sha256": "52f0dc91f1c81328550848c3f4546dcfe777e4f831020df688d772e8a89d6edd",
          "sha1": "1335804386f142172f7da5662eb13db834852f6b",
          "md5": "3b9ecec4aa5b3e65bc9d8eca5dd3572f"
        }
      ]
    }
  ]
}
