{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "mixin",
    "version": "7.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-mixin",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mixin-7.0.57.jar",
          "url": "mixin-7.0.57.jar",
          "size": 4652,
          "sha512": "d1bef4af7d9e283626dc36f8594db8ece47bf7b046205574a41990866ce7cb5d96433931f9cebd007543289e0812f584f4cd45c9f8663d14a67aca4780c19704",
          "sha256": "c0288db3142fb329e4642590ef416b2270e862518f3163380c09755618c8a1b7",
          "sha1": "113c2dcc3a7de2a3c9e03f68b62fc828b9cf88c1",
          "md5": "b92240410e5e66ac6db62f302fd522d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-mixin",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mixin-7.0.57.jar",
          "url": "mixin-7.0.57.jar",
          "size": 4652,
          "sha512": "d1bef4af7d9e283626dc36f8594db8ece47bf7b046205574a41990866ce7cb5d96433931f9cebd007543289e0812f584f4cd45c9f8663d14a67aca4780c19704",
          "sha256": "c0288db3142fb329e4642590ef416b2270e862518f3163380c09755618c8a1b7",
          "sha1": "113c2dcc3a7de2a3c9e03f68b62fc828b9cf88c1",
          "md5": "b92240410e5e66ac6db62f302fd522d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mixin-7.0.57-sources.jar",
          "url": "mixin-7.0.57-sources.jar",
          "size": 2340,
          "sha512": "3be8ae1d41366b08247b916bd2d7a38f51108efc7be9abeb3b8c97d584f7e4ed913c3e19ce6adc314869bee0a2786cc08be5bbe740ae3d0712a5390644aa84cf",
          "sha256": "ad4f4d56c39bfce564a1fcbef837dd9f29c341f4ed6e8ba7ada2f9a4dadeb475",
          "sha1": "81251e8f2ab5f6a1bb92721167c6583fb32e5f6d",
          "md5": "6d878a69fa80238bf909ade1e9748891"
        }
      ]
    }
  ]
}
