{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "platform",
    "version": "7.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.6.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "vanilla",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "userdev",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-platform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "platform-7.0.57.jar",
          "url": "platform-7.0.57.jar",
          "size": 85838,
          "sha512": "20a45a5c708e29b3e55d290a769012d3afbdb0fa7e8c0456259e7c68145b28f493bed44ee07f1b9ae65d06bf0b1799d02fa4f783bf2abb02020ef756bf4d27ed",
          "sha256": "5046522297e21f29d8fcaff7dc81c48ad55f0e020a0fce54613b9ed5d0689d65",
          "sha1": "704ec0d04ed47a68a95808c048ddd23d09af0c97",
          "md5": "456872f08cd169963e7ef3324187272f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.6.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "vanilla",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "userdev",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-platform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "platform-7.0.57.jar",
          "url": "platform-7.0.57.jar",
          "size": 85838,
          "sha512": "20a45a5c708e29b3e55d290a769012d3afbdb0fa7e8c0456259e7c68145b28f493bed44ee07f1b9ae65d06bf0b1799d02fa4f783bf2abb02020ef756bf4d27ed",
          "sha256": "5046522297e21f29d8fcaff7dc81c48ad55f0e020a0fce54613b9ed5d0689d65",
          "sha1": "704ec0d04ed47a68a95808c048ddd23d09af0c97",
          "md5": "456872f08cd169963e7ef3324187272f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "platform-7.0.57-sources.jar",
          "url": "platform-7.0.57-sources.jar",
          "size": 35461,
          "sha512": "28c521b50a6f66fccf1189a50824e6908c6cfa202412648ad3e6c3672416067e09646a075585fa1be8a51c6d660b183168a433ad7e475e21d8bda33f826358fb",
          "sha256": "27e56e858e4f2e0b9583184aee219d6f6c6e309d1f31b6e74c07d986d458cde6",
          "sha1": "010fc1958783f43e24e86a1a4cbe8b6a49423aee",
          "md5": "006d2e7a470c70f1e07e4a939dd16a24"
        }
      ]
    }
  ]
}
