{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "vanilla",
    "version": "7.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-vanilla",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vanilla-7.0.57.jar",
          "url": "vanilla-7.0.57.jar",
          "size": 50958,
          "sha512": "77e999678a6280165562cb955bda3847f0706680453f6b14842c57710f9f009c2289819bffbd6ade8c7a657d97cf97bd9a41fa44cc547ddf5706cd92e4822317",
          "sha256": "8d8eb51bcdd49acc4fdd4dd609060d14ee0cc6d9d07b26409bd7a7d2a45744ad",
          "sha1": "bb25943d3dea526e0ee92dc6995a2e46ea51cc3d",
          "md5": "d79e76922adf3e282830f7f56a204561"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-vanilla",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vanilla-7.0.57.jar",
          "url": "vanilla-7.0.57.jar",
          "size": 50958,
          "sha512": "77e999678a6280165562cb955bda3847f0706680453f6b14842c57710f9f009c2289819bffbd6ade8c7a657d97cf97bd9a41fa44cc547ddf5706cd92e4822317",
          "sha256": "8d8eb51bcdd49acc4fdd4dd609060d14ee0cc6d9d07b26409bd7a7d2a45744ad",
          "sha1": "bb25943d3dea526e0ee92dc6995a2e46ea51cc3d",
          "md5": "d79e76922adf3e282830f7f56a204561"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vanilla-7.0.57-sources.jar",
          "url": "vanilla-7.0.57-sources.jar",
          "size": 21417,
          "sha512": "638ae5a89f4ce6a391770578c923671d2846252578f41bf3e240fda6f3e1e4f2944eb3676732a2c171677b1b1255e660ed667526169ef1e5b22e9cf150f740e0",
          "sha256": "97bb7bb713fb06835aa1dbe9c64514818b25f9f69e1bfc66c83c48e43dd54626",
          "sha1": "d820ffb3198b3807ff42870295643cc52ce9fabc",
          "md5": "da405ea7a1c8c59283759b0e94977ce2"
        }
      ]
    }
  ]
}
