{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "dsl-userdev",
    "version": "7.0.5+asset-redownload",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dsl-userdev-7.0.5+asset-redownload.jar",
          "url": "dsl-userdev-7.0.5+asset-redownload.jar",
          "size": 26532,
          "sha512": "5395969bc3293eef5d46ddc4456cdd8911b2f26ee3cf81ea9c6927f12b704488094763b9a294430f70a2d7d0460f1c5c2ac4ec923e2b8c18445dc943b621c0f6",
          "sha256": "072a649574be81d27a04fc0bf478c363f5aa9913ced04777ec3cbf54b1579007",
          "sha1": "18f916c21fa48cacca1d9393a559ac904c37ad31",
          "md5": "81b21d2b646f15597d8df134d90ff740"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dsl-userdev-7.0.5+asset-redownload.jar",
          "url": "dsl-userdev-7.0.5+asset-redownload.jar",
          "size": 26532,
          "sha512": "5395969bc3293eef5d46ddc4456cdd8911b2f26ee3cf81ea9c6927f12b704488094763b9a294430f70a2d7d0460f1c5c2ac4ec923e2b8c18445dc943b621c0f6",
          "sha256": "072a649574be81d27a04fc0bf478c363f5aa9913ced04777ec3cbf54b1579007",
          "sha1": "18f916c21fa48cacca1d9393a559ac904c37ad31",
          "md5": "81b21d2b646f15597d8df134d90ff740"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dsl-userdev-7.0.5+asset-redownload-sources.jar",
          "url": "dsl-userdev-7.0.5+asset-redownload-sources.jar",
          "size": 8636,
          "sha512": "29778f3b6eb139386e33a2561a031fc621a6faa9a73e12d87e8c2a9a18c2969517ace923be98d06ab41b1a729efe270ce08c8a94c43c8071689f3cda31641b6f",
          "sha256": "e6fe0a2035ad3d916e8f14fd095a4f4e6adcef95eb2b9cbebcc2f052584e98f0",
          "sha1": "a956be3b9263d52b0b559a12d2567572a8a15786",
          "md5": "0f14c2912fd7f43a18a4c100270feb3b"
        }
      ]
    }
  ]
}
