{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "dsl-platform",
    "version": "7.0.5+asset-redownload",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-common",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "utils",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dsl-platform-7.0.5+asset-redownload.jar",
          "url": "dsl-platform-7.0.5+asset-redownload.jar",
          "size": 127065,
          "sha512": "e602a87f296e5c07b7e0966c57f64613e95b8b037920114549cc22574601b7bfa25a013f3f1f91a8ff7050762248251279f368bc905e156fbec9909aeec1b177",
          "sha256": "b86d289e95cd50dfa9dd3012a765980555861ede6cfd701ab61ed69be1f35b24",
          "sha1": "d3cbb147c3afaa65376464ea48fe4766678eb2b7",
          "md5": "66e1ed7cf3330019221f1f55cc9cfab5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-common",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "utils",
          "version": {
            "requires": "7.0.5+asset-redownload"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dsl-platform-7.0.5+asset-redownload.jar",
          "url": "dsl-platform-7.0.5+asset-redownload.jar",
          "size": 127065,
          "sha512": "e602a87f296e5c07b7e0966c57f64613e95b8b037920114549cc22574601b7bfa25a013f3f1f91a8ff7050762248251279f368bc905e156fbec9909aeec1b177",
          "sha256": "b86d289e95cd50dfa9dd3012a765980555861ede6cfd701ab61ed69be1f35b24",
          "sha1": "d3cbb147c3afaa65376464ea48fe4766678eb2b7",
          "md5": "66e1ed7cf3330019221f1f55cc9cfab5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dsl-platform-7.0.5+asset-redownload-sources.jar",
          "url": "dsl-platform-7.0.5+asset-redownload-sources.jar",
          "size": 17011,
          "sha512": "ab6813531a4bbed84bdeb9e4f4875d45da166fb7c30bd59b58dc217287aacb48737ab1c0219a847dafeb5d7e40b7bf69f29defe359996c70eef0355263d6a4b3",
          "sha256": "3fe921fb566f98a33de1eaec6cf88d8b5d801b4d6ff09a444ee3e9aedc51f31d",
          "sha1": "965017352300913863d892ade9dd967713b9685b",
          "md5": "0fbbf237917d8a9a333b4b493ee1ab87"
        }
      ]
    }
  ]
}
