{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.gradle",
    "module": "userdev",
    "version": "7.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-userdev",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "userdev-7.0.57.jar",
          "url": "userdev-7.0.57.jar",
          "size": 49188,
          "sha512": "fb2f55e238f238a537024c133a4f27ea0bfa5c00d8956bd1ada2270085dd647999ac3d0beab4a41c8943645b2ddb5268310e391c011809a5a33a9dece9b94da1",
          "sha256": "1523c983c61452c57441d488d5316fd731d0e318c02d718db45faff405f0acda",
          "sha1": "5ff9e13cdcf6e840e44def8341da284220715434",
          "md5": "0281bd2d3af4bfca34d301de450b6a20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "base"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "groovydslimprover",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovydslimprover",
              "type": "jar",
              "extension": "jar",
              "classifier": "runtime"
            }
          }
        },
        {
          "group": "net.neoforged.gradle",
          "module": "common",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "neoform",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.gradle",
          "module": "dsl-userdev",
          "version": {
            "requires": "7.0.57"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "userdev-7.0.57.jar",
          "url": "userdev-7.0.57.jar",
          "size": 49188,
          "sha512": "fb2f55e238f238a537024c133a4f27ea0bfa5c00d8956bd1ada2270085dd647999ac3d0beab4a41c8943645b2ddb5268310e391c011809a5a33a9dece9b94da1",
          "sha256": "1523c983c61452c57441d488d5316fd731d0e318c02d718db45faff405f0acda",
          "sha1": "5ff9e13cdcf6e840e44def8341da284220715434",
          "md5": "0281bd2d3af4bfca34d301de450b6a20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "userdev-7.0.57-sources.jar",
          "url": "userdev-7.0.57-sources.jar",
          "size": 21523,
          "sha512": "8bd72666f25655b8f590768fa516fd61b6adf05d22ca60408920b73df421d73124a948391d4363af78167eb3af5f92568ee03328a188f85071b4d143f2f13f68",
          "sha256": "c5e2d1696ffdcfb853740e4c7fadfed29b04b84188fe868d99511e0d4bed48b8",
          "sha1": "e862737f83048a1086190cf4dfc21924cd8c0bbc",
          "md5": "916b95a6357c17dba346a668f4694c78"
        }
      ]
    }
  ]
}
